### ISSUE TITLE
Bold ANSI code not supported

### ISSUE THREAD

**Issue by daveyarwood** [m00qek/baleia.nvim#1]
Baleia is working great for the most part, but one thing I noticed is that the `\e[1m` (bold) escape code doesn't appear to be working. For example:
![2021-09-20-123314_749x207_scrot](https://user-images.githubusercontent.com/4909079/134039601-2dfea81e-e8ca-4791-9aee-ea9c712c5940.png)

See also:
https://github.com/Olical/conjure/issues/53#issuecomment-552612529
https://github.com/chrisbra/Colorizer/issues/76

**Comment by m00qek** [comment]
Seems like it is only setting bold settings for `cterm`. If you run
```vim
:highlight BaleiaColors_B_none_none
```
the result will be
```vim
BaleiaColors_B_none_none cterm=bold
```
and the correct should be 
```vim
highlight BaleiaColors_B_none_none cterm=bold gui=bold
```
I'm going to make a patch 🔜

**Comment by daveyarwood** [comment]
That fixed it. Nice!
