### ISSUE TITLE
Doesn't work in read-only buffers, even with strip_ansi_codes = false

### ISSUE THREAD

**Issue by SevereOverfl0w** [m00qek/baleia.nvim#12]
I have:

```viml
  let s:baleia = luaeval("require('baleia').setup({ strip_ansi_codes = false, log = 'DEBUG' })")
  command! BaleiaColorize call s:baleia.once(bufnr('%'))
  command! BaleiaLogs call s:baleia.logger.show()
```

But in read-only buffers (e.g. quickfix / fireplace's :Last command) colors aren't highlighted, just ignored:

```
ERROR vim.api.nvim_buf_set_text
    | {
    |   params = {
    |     buffer = 16,
    |     end_col = 53,
    |     end_row = 14,
    |     lines = { "... removed ..." },
    |     start_col = 0,
    |     start_row = 0
    |   },
    |   result = "Buffer is not 'modifiable'"
    | }
```

some highlighting seems to take place, but it doesn't colour the text it's supposed to.

**Comment by m00qek** [comment]
Hey I've fixed the buggy `strip_ansi_codes = false` behavior _but _ if you are trying to colorize the quickfix I believe using [BufReadPost](https://github.com/m00qek/baleia.nvim#automatically-colorize-text-added-to-the-quickfix-window) is easier
