### ISSUE TITLE
Setup with lazy.nvim

### ISSUE THREAD

**Issue by jlaunay** [m00qek/baleia.nvim#17]
Any hint to setup baleia with lazy.nvim ?

**Comment by m00qek** [comment]
It should be very similar to what is described on the readme 🤔 
I have submitted [a PR](https://github.com/LazyVim/LazyVim/pull/2179/files#diff-fc70d762ecd57a607bb52fa96c9e51694162821f69c5de7ba7793b20a5f55455R43) for LazyVim that configures baleia and conjure, maybe it can inspire you.
I will soon add lazy.nvim instructions alongside the other installers

**Comment by m00qek** [comment]
I added instructions to the README
