### ISSUE TITLE
Any way to use with command window / more-pager?

### ISSUE THREAD

**Issue by hahuang65** [m00qek/baleia.nvim#18]
I'm trying to use this to colorize `git push` and `git commit` output (because sr.ht outputs color when you have an associated CI build, and because `pre-commit` hooks also have color.

Example:
```
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: ^[[1mBuild started:^[[0m
remote: ^[[94mhttps://builds.sr.ht/~hwrd/job/1125600^[[0m [mirror.yml]
To git.sr.ht:~hwrd/nvim-config
 + 6709920...f06e48a main -> main (forced update)
Press ENTER or type command to continue
```

However, these just output into the command pager (`:h pager`). As far as I can tell, there's no buffer associated with this?

Is there any way I can use baleia to colorize this output?

**Comment by m00qek** [comment]
I'm not exactly sure, but I don't think it is possible to create highlight groups outside of buffers 😕
