### ISSUE TITLE
does this works on ":!" (external command)

### ISSUE THREAD

**Issue by Ferno2k** [m00qek/baleia.nvim#22]
![Screenshot 2024-04-28 161103](https://github.com/m00qek/baleia.nvim/assets/109463444/3aab069a-78a1-4153-89d8-b0081ad4c72d)

I am new to nvim was trying :! external command found it to be more useful then :term but it doesn't support ANSI color codes.  My question is does plugin help me to solve this type of issue?

**Comment by m00qek** [comment]
Hey there, thanks for reaching out.

No this will not work for this case. This plugin can only change text in buffers.
