### ISSUE TITLE
Sporadic "start_row out of bounds" error after updating

### ISSUE THREAD

**Issue by daveyarwood** [m00qek/baleia.nvim#3]
Hello,

Over the last few days, I've started seeing this error happen sporadically while developing Clojure code with Conjure. I'm not sure what's causing it. I am using the development branch of nvim (`nvim --version` returns `NVIM v0.7.0-dev`), and I know that it's been updated recently, whereas the last commit of Baleia is from October, so I suspect that it might be related to some change in Neovim?

```
Error executing vim.schedule lua callback: /home/dave/.vim/bundle/baleia.nvim/lua/baleia.lua:51: start_row out of bounds
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        /home/dave/.vim/bundle/baleia.nvim/lua/baleia.lua:51: in function </home/dave/.vim/bundle/baleia.nvim/lua/baleia.lua:46>
```

**Comment by m00qek** [comment]
Hey, sorry for the late response. I'm using the latest stable neovim... let me try using baleia with the latest unstable.
Anyway, I'm thinking in adding a logging feature for the plugin 🚧

**Comment by daveyarwood** [comment]
For what it's worth, I totally forgot about this issue. I haven't noticed it at all recently. So whatever the problem was, it may have fixed itself!

**Comment by m00qek** [comment]
Just pushed some logging capabilities to the main branch. If you see this happening again open an issue with logs :)

**Comment by daveyarwood** [comment]
Awesome, will do
