### ISSUE TITLE
module 'baleia' not found

### ISSUE THREAD

**Issue by Sangdol** [m00qek/baleia.nvim#4]
Hello,

I'm trying Conjure for Clojure and found this plugin in the Ansi Color thread ([link](https://github.com/Olical/conjure/issues/53)).

I installed Baleia with Plug

```vim
  Plug 'm00qek/baleia.nvim', { 'tag': 'v1.1.0' }
  let g:conjure#log#strip_ansi_escape_sequences_line_limit = 0
  let s:baleia = luaeval("require('baleia').setup { line_starts_at = 3 }")
  autocmd BufWinEnter conjure-log-* call s:baleia.automatically(bufnr('%'))
```

but I faced an errer while running this `luaeval("require('baleia').setup { line_starts_at = 3 }")`

```log
E5108: Error executing lua [string "luaeval()"]:1: module 'baleia' not found:
        no field package.preload['baleia']
        no file './baleia.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20211210/share/luajit-2.1.0-beta3/baleia.lua'
        no file '/usr/local/share/lua/5.1/baleia.lua'
        no file '/usr/local/share/lua/5.1/baleia/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20211210/share/lua/5.1/baleia.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20211210/share/lua/5.1/baleia/init.lua'
        no file './baleia.so'
        no file '/usr/local/lib/lua/5.1/baleia.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20211210/lib/lua/5.1/baleia.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string "luaeval()"]:1: in main chunk
```

It seems luaeval can't find `baleia`. How could I fix this?

Thanks.

**Comment by m00qek** [comment]
Hey 👋🏽 
Are you sure that plug installed Baleia properly?

**Comment by Sangdol** [comment]
Hi, yes I've checked it out and even tried to copy the installed Baleia to other folders to see if it works. Does it work well with Plug on your side? After reading the [`lua-require`](https://neovim.io/doc/user/lua.html#lua-require) section I wasn't sure if it could load a file in a custom plug folder which is `~/.vim/plugged` in my case.

**Comment by m00qek** [comment]
I don't use Plug myself. Are you calling Plug between `call plug#begin()` and `call plug#end()`?

**Comment by Sangdol** [comment]
Hey, 

I've found out the reason for the issue. I have to load a lua module after `call plug#end()` since the `plug#end()` function updates `&runtimepath`.

The problem was that I was calling this function right after the `Plug 'm00qek/baleia.nvim', { 'tag': 'v1.1.0' }` line like this:

```vim
Plug 'm00qek/baleia.nvim', { 'tag': 'v1.1.0' }
let s:baleia = luaeval("require('baleia').setup { }")
```

I'm closing the issue. 

Thanks for your support.
